### ISSUE TITLE
Default page not loading ('/')

### ISSUE THREAD

**Issue by kracekumar** [meadsof/mead#2]
I have configured mead , db is created and when i access the www.yyy.com for which mead is configured , error meaasge: "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application." .When I looked into apache log file I din get any error message. I have not changed any default mead config.

When tried in localhost, jinja2.exceptions.TemplateNotFound.

**Comment by abdounasser202** [comment]
it's now working. 

https://github.com/meadsof/mead/tree/5b61a88322cacc96aaa6cdb46e25bf4f34b7ccdb
